title: Sazzad Hussain Farhaan
#logo: /assets/img/photo.png
#description: text below image
# show_downloads: true




personal_information:
  address: Dhanmondi 7A, Dhaka, Bangladesh
  email: shfarhaan21@gmail.com
  phone: +880 1685 170 845
  linkedin: www.linkedin.com/in/shfarhaan/
  github: github.com/shfarhaan

theme: jekyll-theme-minimal
