title: Sazzad Hussain Farhaan
# logo: /assets/shfarhaan.png
description: Address - Dhanmondi 7A, Dhaka, Bangladesh
description: email - shfarhaan21@gmail.com
theme: jekyll-theme-minimal




  # email: shfarhaan21@gmail.com
  # phone: +880 1685 170 845
  # linkedin: www.linkedin.com/in/shfarhaan/
  # github: github.com/shfarhaan

# show_downloads: true
