title: Sazzad Hussain Farhaan
# logo: /assets/shfarhaan.png
description: Dhanmondi 7A, Dhaka, Bangladesh
personal_information:
  name: Sazzad Hussain Farhaan
  address: 
  email: shfarhaan21@gmail.com
  phone: +880 1685 170 845
  linkedin: www.linkedin.com/in/shfarhaan/
  github: github.com/shfarhaan
theme: jekyll-theme-minimal


# show_downloads: true
