title: Sazzad Hussain Farhaan
logo: /assets/shfarhaan.png

theme: jekyll-theme-minimal

# show_downloads: true
# personal_information:
  # name: Sazzad Hussain Farhaan
  # address: Dhanmondi 7A, Dhaka, Bangladesh
  # email: shfarhaan21@gmail.com
  # phone: +880 1685 170 845
  # linkedin: www.linkedin.com/in/shfarhaan/
  # github: github.com/shfarhaan