title: Sazzad Hussain Farhaan
logo: /assets/assets/shfarhaan.png
description: >
  <head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sazzad Hussain Farhaan - CV</title>

  <!-- Font Awesome icons (you may need to include the Font Awesome library) -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  </head>
  
  
  <h2>Personal Information</h2>
 
  <p><i class="fas fa-envelope"></i> <strong>Email:</strong> shfarhaan21@gmail.com</p>
  <p><i class="fas fa-phone"></i> <strong>Phone:</strong> +880 1685 170 845</p>
  <p><i class="fab fa-linkedin"></i> <strong>LinkedIn:</strong> <a href="www.linkedin.com/in/shfarhaan/" target="_blank">shfarhaan</a></p>
  <p><i class="fab fa-github"></i> <strong>GitHub:</strong> <a href="github.com/shfarhaan" target="_blank">shfarhaan</a></p>

theme: jekyll-theme-minimal

# show_downloads: true
# personal_information:
  # name: Sazzad Hussain Farhaan
  # address: Dhanmondi 7A, Dhaka, Bangladesh
  # email: shfarhaan21@gmail.com
  # phone: +880 1685 170 845
  # linkedin: www.linkedin.com/in/shfarhaan/
  # github: github.com/shfarhaan