# title: Sazzad Hussain Farhaan
# logo: /assets/shfarhaan.png
# description: *address:* Dhanmondi 7A, Dhaka, Bangladesh
# description: *email:* shfarhaan21@gmail.com
# description: *phone:* +880 1685 170 845
# description: *linkedin:* www.linkedin.com/in/shfarhaan/
# description: *github:* github.com/shfarhaan

**Sazzad Hussain Farhaan**:
  logo: /assets/shfarhaan.png
  description:
    - *address:* Dhanmondi 7A, Dhaka, Bangladesh
    - *email:* shfarhaan21@gmail.com
    - *phone:* +880 1685 170 845
    - *linkedin:* www.linkedin.com/in/shfarhaan/
    - *github:* github.com/shfarhaan




theme: jekyll-theme-minimal


# show_downloads: true
