title: Sazzad Hussain Farhaan
# logo: /assets/shfarhaan.png
description:

theme: jekyll-theme-minimal


  # - *address:* Dhanmondi 7A, Dhaka, Bangladesh
  # - *email:* shfarhaan21@gmail.com
  # - *phone:* +880 1685 170 845
  # - *linkedin:* www.linkedin.com/in/shfarhaan/
  # - *github:* github.com/shfarhaan



# show_downloads: true
