title: Sazzad Hussain Farhaan
#logo: /assets/img/photo.png
#description: text below image
# show_downloads: true
theme: jekyll-theme-minimal



## Personal Information
- **Name:** Sazzad Hussain Farhaan
- **Address:** Dhanmondi 7A, Dhaka, Bangladesh
- **Email:** shfarhaan21@gmail.com
- **Phone:** +880 1685 170 845
- **LinkedIn:** [shfarhaan](www.linkedin.com/in/shfarhaan/)
- **GitHub:** [shfarhaan](github.com/shfarhaan)
